apiVersion: v1
kind: Service
metadata:
  name: shortlet-service
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: shortlet-service
  type: NodePort
  # loadBalancerIP: 35.201.71.84